default_platform: ios

platform: ios do
        before_all do
            cocoapods
        end

    desc“ Runs all the tests”
lane: test do
        scan(
            scheme: “MarvelHeroes”,
            code_coverage: true
        )
    end

desc“ Runs coverage”
lane: coverage do
        test
    slather(
        travis: true,
        scheme: “MarvelHeroes”,
        coveralls: true,
        proj: “MarvelHeroes.xcodeproj”,
        workspace: “MarvelHeroes.xcworkspace”
    )

end

end
